### ISSUE TITLE
Problems with encoding for column width calculation

### ISSUE THREAD

**Issue by fidelaznar** [ickc/pantable#13]
The following table could not be compiled:
```table
---
caption: 'Áreas ...'
alignment: LLL
table-width: 2/3
markdown: True
---
Código,Áreas,N.Horas
DS, Discrete Structures, 43
```

Solution: force UTF8 encoding. Add in line 60 of "pantable.py" the following lines: 
reload(sys)
sys.setdefaultencoding('utf8')

**Comment by ickc** [comment]
@fidelaznar, which Python version were you using?

**Comment by fidelaznar** [comment]
Python 2.7.13

**Comment by ickc** [comment]
It is a problem of the CSV module in Python2. Are you sure your fix would fix the unicode problem in Pyhton2?

I'm considering using another CSV writer/reader such as Pandas (for various reasons including performance and this). But it's a big dependency. Let me know your opinion on this.

**Comment by fidelaznar** [comment]
With this lines I've compiled a lot of tables without a problem using Unicode Chars. If the input is Unicode It should work.

**Comment by ickc** [comment]
Also see #21

**Comment by ickc** [comment]
@fidelaznar, please check pantable v0.11 if #25 fixes your problem. Thanks.
