### ISSUE TITLE
image link in a table cell makes error at pdf output

### ISSUE THREAD

**Issue by K4zuki** [ickc/pantable#20]
- OSX Sierra(other OSes are not tested yet)
- pandoc `1.19.2.1`
  - `-t latex -o pdf.pdf` option
- pantable `0.10.4/0.10.5`

---

# Description
1. When adding some image(s) in a table cell, no matter external file or code block, pandoc raises 
error and fails to output pdf.

```
$ pandoc markdown.md -t latex --filter=pantable -o pdf.pdf
! Misplaced \noalign.
\caption ->\noalign
                    \bgroup \@ifnextchar [{\egroup \LT@c@ption \@firstofone ...
l.132 \caption
pandoc: Error producing PDF
```
2. Tested if latex output differs by filtering: **pantable generated source is not identical to inline table**
  - ```$ pandoc markdown.md -t latex --latex-engine=xelatex --filter=pantable -o latex.tex```
  - ```$ pandoc markdown.md -t latex --latex-engine=xelatex                   -o latex2.tex```

```
$ diff latex.tex latex2.tex
...
> \begin{longtable}[]{@{}ll@{}}
> \caption{CAPTION}\tabularnewline
> \toprule
> \begin{minipage}[b]{0.24\columnwidth}\raggedright\strut
> image\strut
> \end{minipage} & \begin{minipage}[b]{0.71\columnwidth}\raggedright\strut
> \begin{figure}
> \centering
> \includegraphics{./png.png}
> \caption{caption}
> \end{figure}
> \strut
> \end{minipage}\tabularnewline
...
```

---

From the diff **the filtered latex contains `\begin{figure}`...`\end{figure}` block while inline does not.**
Can you confirm if this is a bug in pantable/panflute or pandoc itself?

---

# Source files
## `png.png`
![png.png](https://user-images.githubusercontent.com/9379328/28887071-c3706cf8-77f6-11e7-877c-078c4e89a9c3.png)

## `csv.csv`
```
image,![caption](./png.png)
text,this is a text
,foo
bar,
```

## `markdown.md`
`````markdown
# include image by standard way

![caption](./png.png)

# include image in inline grid table

Table: CAPTION

+-------+-----------------------+
| image | ![caption](./png.png) |
+=======+=======================+
| text  | this is a text        |
+-------+-----------------------+
|       | foo                   |
+-------+-----------------------+
| bar   |                       |
+-------+-----------------------+

# include image in grid table generated by pantable

```table
---
# table-width:
header: True
markdown: True
caption: CAPTION
include: csv.csv
---
```

# source files

- `markdown.md`
- `csv.csv`
- `png.png`

# commands

1. ```pandoc markdown.md -t html                         --filter=pantable -o html.html```
1. ```pandoc markdown.md -t latex --latex-engine=xelatex --filter=pantable -o latex.tex```
1. ```pandoc markdown.md -t latex --latex-engine=xelatex                   -o latex2.tex```
1. ```pandoc markdown.md -t latex --latex-engine=xelatex --filter=pantable -o pdf.pdf```
1. ```pandoc markdown.md -t latex --latex-engine=xelatex                   -o pdf.pdf```
`````

**Comment by ickc** [comment]
It's an upstream bug. See jgm/pandoc#3836.

**Comment by ickc** [comment]
@K4zuki, it's fixed in https://github.com/jgm/pandoc/commit/3504915e63c68c3a4e91b8dcccb90c93435cf212

I verified this works using https://github.com/pandoc-extras/pandoc-nightly/releases/latest

either wait for the next release of use pandoc-nightly for the meanwhile (which might have unstable features though.)

**Comment by K4zuki** [comment]
@ickc Thank you for the help and information!
I can wait for a while till next pandoc release.
