### ISSUE TITLE
TravisCI fails for Py3.3

### ISSUE THREAD

**Issue by reenberg** [ickc/pantable#29]
With the introduced [dependency on `setuptools>=20.6.8`](https://github.com/ickc/pantable/commit/13dfb9b78c94bca739ec065c867fd253a6793a90) the travis build for python 3.3 fails, because the travis python 3.3 virtual environment doesn't contain a new enough `setuptools`:

```
[...]
    AssertionError: Setuptools version 20.6.8 or heigher is required.  Updated it using `pip install -U setuptools`.
[...]
```

**Comment by reenberg** [comment]
Sure thing.  The virtual environment for Py3.3 contains

> mock (2.0.0)
> nose (1.3.7)
> numpy (1.11.1)
> pbr (1.10.0)
> pip (9.0.1)
> py (1.4.31)
> pytest (2.9.2)
> setuptools (18.0.1)
> six (1.10.0)
> wheel (0.29.0)

**Comment by ickc** [comment]
Thanks! Sorry I didn't read this until today (the big day that pandoc 2.0 is released so I have to come checking).

Next time you can use [Closing Issues via Pull Requests](https://github.com/blog/1506-closing-issues-via-pull-requests).

**Comment by reenberg** [comment]
@ickc; I thought I did, but it seems that I got the reference wrong or something?

I had "This fixes pantable/#29" in the commit message, and as you see above, it also picked up the reference to this issue : "reenberg added a commit to reenberg/pantable that referenced this issue 21 days ago"... So don't get why it didn't close this when you merged it.

**Comment by ickc** [comment]
I guess it was the extra “pantable/“. You can just refer to #29 since it is the same repo.

**Comment by ickc** [comment]
By the way, you could file an issue to GitHub so that it might becomes smarter. ;)
