### ISSUE TITLE
Does pantable support footnote?

### ISSUE THREAD

**Issue by gepcel** [ickc/pantable#35]
Hi, I like pantable, and use it a lot. But I can't get footnotes done.

Here is my example:

testfootnote.md
````
# First paragraph

Some text first[^note1].

```table
---
caption: Caption of table[^note2]
markdown: true
---
Col1, Col2
A, B
```
[^note1]: Some description here.

[^note2]: Description for table.
````

Convert it to pdf using `pandoc testfootnote.md -t latex --filter=pantable -o test.pdf`.
`note1` works, but `note2` doesn't. Any way I can may make this work?

Thanks

**Comment by ickc** [comment]
Reopen to ensure I check this behavior. Probably no solution but at least document it.
