### ISSUE TITLE
Allowing caller to specify the csv dialect

### ISSUE THREAD

**Issue by fralau** [ickc/pantable#36]
Thanks a lot for this good development of pantable. Currently, it supports the default format of csv (essentially commas as separator).

It would be good if it also allowed different csv formats (e.g. semicolons as separator).

I would like to define something according to those lines in pantable.py:
```
dialect = csv.excel
dialect.delimiter = ';'

def read_data(include, data, delimiter, dialect):
     ....
    raw_table_list = list(csv.reader(file, delimiter=delimiter, dialect=dialect))
```

As a suggestion, there could be two complementary approaches:

  - command-line: allow the caller to specify dialect and delimiters from directly from bash, as environment variables, e.g. `export PANTABLE_DELIMITER=';' ; export PANTABLE_DIALECT=excel` (my preferred one, since "Excel with ;" is a very workable default)
  - as parameters: specify the delimiter and dialect in the yaml header of the markdown file.

What would you think about this?

**Comment by ickc** [comment]
I had thought about this in the beginning, [started a discussion on pandoc-discuss about filter options](https://groups.google.com/d/msg/pandoc-discuss/LIAfgkZKUiE/_KfI3VI6EgAJ). Since none of the suggestions there has been materialized, probably we should just use env. var. to pass filter options.

**Comment by ickc** [comment]
c.f. #8

**Comment by fralau** [comment]
Indeed I had tested this and found that command-line arguments did not work; pity because it would make sense.

This is why I suggested, as a workaround, to allow environment variables (e.g. `export PANTABLE_DELIMITER=';'`).

**Comment by ickc** [comment]
I just pushed v0.12.1 that has a csv-kwargs option. See the doc for (not so much) details. This is a case that no test is written. So I'd appreciate if you could add an example at the end of `tests/test_pantable.md`.
