### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rannochRavenna** [ickc/pantable#39]
When I attempt to run this after a fresh install, I get the following error:

``
~ $ pandoc -F pantable -o test simple.csv 
/Library/Python/2.7/site-packages/panflute/autofilter.py:163: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see https://click.palletsprojects.com/python3/
``

Am I doing something wrong?

**Comment by ickc** [comment]
Can you provide a reproducible minimal working example?

Note that it could be because of Python 2's unicode support problem. And as of v0.12 pantable is dropping Python 2 support.
