### ISSUE TITLE
Relicensing to BSD 3-clause license

### ISSUE THREAD

**Issue by ickc** [ickc/pantable#50]
Hi, @reenberg, @alerque, @gepcel,

I plan to relicense this repository to BSD 3-clause license similar to the one panflute use, the main dependency of this project. pandocfilters by jgm uses the same license, which inspires panflute.

Note that pandoc itself is GPLv2+, so for the whole stack to work it would still be GPLv2+. The only thing relaxed here would be from GPLv3 to GPLv2+.

You have contributed to this repository. So I'm asking you explicit permissions to do so.

P.S. I am not a lawyer. Feel free to inform me better.

**Comment by gepcel** [comment]
I don't really know the differences between licenses. I've no objections here.

**Comment by alerque** [comment]
Yes, I am okay with my contributions to this project being licensed using the BSD 3-clause license. Thanks for asking.

I'm not a lawyer either but as I understand it... Keep in mind that you can't _remove_ the GPLv3 status from previously contributed code (even your own). What's been released to date will remain available for use under the terms of the old license. What happens in a re-license situation like this is that all _future_ code from this point on will be licensed under the terms of the new license and –the part you're asking for permission for here– all the existing code to date needs to be _additionally_ released for use under the terms of the new license.

**Comment by ickc** [comment]
I may have misunderstood you but I think it is not true.

Since we are the authors we can choose whatever license we want. At the point of relicensing the same code has been released twice in 2 licenses. And future commits will be under the new license only. So say (in a commit just before) v0.13 is relicensed under BSD 3 clause, then <=v0.13 is under GPLv3, >=v0.13 is under BSD 3 clause. (v0.13 will be dual licensed.)

Dual licensing is often used, relicensing less so (as it would requires all authors to agree.) I think there’s at least 2 heroic relicensing, VLC and Mozilla’s Firefox(?), which involves a lot of authors and a ton of effort to track then down to agree. Some projects like Google’s May have a more intrusive approach that requires contributors to sign off an agreement to allow them to relicense it into whatever license they want in the future.

(Since BSD 3 clause is compatible with GPLv3, it is only relaxing the requirement. Ie it shouldn’t affects any project depending on it.)

**Comment by alerque** [comment]
I may have been using poor phrasing there, it  actually sounds like we have roughly the same idea anyway. Carry on.

**Comment by ickc** [comment]
@reenberg, any objection?

**Comment by reenberg** [comment]
Sorry, vacation.

I'm on the same vagon as @gepcel. By all means do what is best for the
project.
